apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: react-nodejs-mysql
spec:
  ports:
    - port: 3306
  selector:
    app: react-nodejs-mysql
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: react-nodejs-mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: react-nodejs-mysql
spec:
  selector:
    matchLabels:
      app: react-nodejs-mysql
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: react-nodejs-mysql
        tier: mysql
    spec:
      containers:
      - image: mannmae/fullstack-mysql:63
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: myapp
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
